plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
    
packageExtensions:
  webpack@*:
    peerDependencies:
      webpack-cli: "*"
      # Upgrade of webpack-cli is blocked by https://github.com/webpack/webpack-cli/issues/1126
  webpack-dev-server@*:
    peerDependencies:
      webpack-cli: "*"
  "@webpack-cli/package-utils@*":
    dependencies:
      # Wait for next beta.
      # https://github.com/webpack/webpack-cli/issues/1494
      cross-spawn: "*"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
